{
 "title": "JVMs",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Process average",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.total.norm.pct",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "System average",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.process.cpu.total.norm.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Average",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.free",
       "id": "1",
       "inlineScript": "1 - _value / doc[\"system.memory.total\"].value",
       "meta": {},
       "settings": {
        "script": {
         "inline": "1 - _value / doc[\"system.memory.total\"].value"
        }
       },
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Avg. used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.memory.heap.used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Avg. limit",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.memory.heap.max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Avg. committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.memory.heap.committed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Avg. committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.memory.non_heap.committed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Avg. used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.memory.non_heap.used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Avg.",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.thread.count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Garbage collection per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Avg.",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.gc.count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Garbage collection time spent per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Avg.",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvm.gc.time",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}