{
 "title": "Contacts, Motion, & Switches",
 "tags": [
  "smartthings",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "contacts",
    "label": "Contacts",
    "query": "label_values(smartthings_contact_sensor_contact, label)"
   },
   {
    "name": "motion",
    "label": "Motion",
    "query": "label_values(smartthings_motion_sensor_motion, label)"
   },
   {
    "name": "switches",
    "label": "Switches",
    "query": "label_values(smartthings_switch_switch, label)"
   }
  ]
 },
 "panels": [
  {
   "title": "Contacts",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (label)(smartthings_contact_sensor_contact{label=~\"$contacts\"})",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Switches",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 31, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (label)(smartthings_switch_switch{label=~\"$switches\"})",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Motion",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (label)(smartthings_motion_sensor_motion{label=~\"$motion\"})",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}