{
 "title": "Doors, Lights, & Motion",
 "tags": [
  "smartthings",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Switches",
    "label": "Switches",
    "query": "label_values(smartthings_switch_switch, label)"
   }
  ]
 },
 "panels": [
  {
   "title": "Doors",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (label)(smartthings_contact_sensor_contact)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Lights",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 31, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (label)(smartthings_switch_switch{label=~\"$Switches\"})",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Motion Senors",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (label)(smartthings_motion_sensor_motion{instance=\"app04.tylephony.com\"})",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}