{
 "title": "Thermostats",
 "tags": [
  "smartthings",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "sum by (label) (smartthings_thermostat_thermostat_setpoint_degree_fahrenheit)",
     "legendFormat": "Setpoint: {{label}}"
    },
    {
     "expr": "sum by (label) (avg_over_time(smartthings_thermostat_temperature_degree_fahrenheit[1h]))",
     "legendFormat": "Actual: {{label}}"
    }
   ]
  },
  {
   "title": "Thermostate Mode",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (label) (smartthings_thermostat_thermostat_mode)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Operating State",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (label) (smartthings_thermostat_thermostat_operating_state)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Fan Mode",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (label) (smartthings_thermostat_thermostat_fan_mode)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (label) (avg_over_time(smartthings_relative_humidity_measurement_humidity_percent[3h]))",
     "legendFormat": "Humidity: {{label}}"
    }
   ]
  },
  {
   "title": "Heating Set Point",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (label) (smartthings_thermostat_heating_setpoint_degree_fahrenheit)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Cooling Set Point",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (label) (smartthings_thermostat_cooling_setpoint_degree_fahrenheit)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Power Source",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (label) (smartthings_power_source_power_source{device_type_name=\"Enhanced Z-Wave Plus Thermostat with Temperature, Humidity and Auto Time setting\"})",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (label) (avg_over_time(smartthings_battery_battery_percent{device_type_name=\"Enhanced Z-Wave Plus Thermostat with Temperature, Humidity and Auto Time setting\"}[30m]))",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}