{
 "title": "Weather - Darksky",
 "tags": [
  "darksky",
  "prometheus"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_apparent_temperature[1h])",
     "legendFormat": "Apparent Temperature"
    },
    {
     "expr": "avg_over_time(darksky_temperature[1h])",
     "legendFormat": "Temperature"
    },
    {
     "expr": "avg_over_time(darksky_dew_point[1h])",
     "legendFormat": "Dew Point"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_wind_gust[1h])",
     "legendFormat": "Wind Gust"
    },
    {
     "expr": "avg_over_time(darksky_wind_speed[1h])",
     "legendFormat": "Wind Speed"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(darksky_bearing_degree[30m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "wind_deg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Nearest Storm Distance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "yaxes": [
    { "format": "lengthmi" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_nearestStormDistance[30m])",
     "legendFormat": "Nearest Storm Distance"
    }
   ]
  },
  {
   "title": "Precipitation Intensity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "in" } },
   "yaxes": [
    { "format": "in" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_precipitation_intensity[15m])",
     "legendFormat": "Precipitation Intensity"
    }
   ]
  },
  {
   "title": "Precipitation Probability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_precipitation_probability[15m])",
     "legendFormat": "Precipitation Probability"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_humidity[30m])",
     "legendFormat": "Humidity"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_pressure_mbar[30m])",
     "legendFormat": "Pressure"
    }
   ]
  },
  {
   "title": "Cloud Cover",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_cloud_cover[30m])",
     "legendFormat": "Cloud Cover"
    }
   ]
  },
  {
   "title": "Visiblity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "yaxes": [
    { "format": "lengthmi" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_visibility[30m])",
     "legendFormat": "Visibility"
    }
   ]
  },
  {
   "title": "Ozone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "DU" } },
   "yaxes": [
    { "format": "DU" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(darksky_ozone_dobson[30m])",
     "legendFormat": "Ozone"
    }
   ]
  }
 ]
}